//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokemonLibrary.LanguageResources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amorphous.
        /// </summary>
        public static string EggGroup_Amorphous {
            get {
                return ResourceManager.GetString("EggGroup_Amorphous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug.
        /// </summary>
        public static string EggGroup_Bug {
            get {
                return ResourceManager.GetString("EggGroup_Bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ditto.
        /// </summary>
        public static string EggGroup_Ditto {
            get {
                return ResourceManager.GetString("EggGroup_Ditto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon.
        /// </summary>
        public static string EggGroup_Dragon {
            get {
                return ResourceManager.GetString("EggGroup_Dragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fairy.
        /// </summary>
        public static string EggGroup_Fairy {
            get {
                return ResourceManager.GetString("EggGroup_Fairy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string EggGroup_Field {
            get {
                return ResourceManager.GetString("EggGroup_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flying.
        /// </summary>
        public static string EggGroup_Flying {
            get {
                return ResourceManager.GetString("EggGroup_Flying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grass.
        /// </summary>
        public static string EggGroup_Grass {
            get {
                return ResourceManager.GetString("EggGroup_Grass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human-Like.
        /// </summary>
        public static string EggGroup_HumanLike {
            get {
                return ResourceManager.GetString("EggGroup_HumanLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mineral.
        /// </summary>
        public static string EggGroup_Mineral {
            get {
                return ResourceManager.GetString("EggGroup_Mineral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster.
        /// </summary>
        public static string EggGroup_Monster {
            get {
                return ResourceManager.GetString("EggGroup_Monster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undiscovered.
        /// </summary>
        public static string EggGroup_Undiscovered {
            get {
                return ResourceManager.GetString("EggGroup_Undiscovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string EggGroup_Unknown {
            get {
                return ResourceManager.GetString("EggGroup_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water 1.
        /// </summary>
        public static string EggGroup_Water1 {
            get {
                return ResourceManager.GetString("EggGroup_Water1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water 2.
        /// </summary>
        public static string EggGroup_Water2 {
            get {
                return ResourceManager.GetString("EggGroup_Water2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water 3.
        /// </summary>
        public static string EggGroup_Water3 {
            get {
                return ResourceManager.GetString("EggGroup_Water3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug.
        /// </summary>
        public static string Type_Bug {
            get {
                return ResourceManager.GetString("Type_Bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Type_Dark {
            get {
                return ResourceManager.GetString("Type_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon.
        /// </summary>
        public static string Type_Dragon {
            get {
                return ResourceManager.GetString("Type_Dragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric.
        /// </summary>
        public static string Type_Electric {
            get {
                return ResourceManager.GetString("Type_Electric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fairy.
        /// </summary>
        public static string Type_Fairy {
            get {
                return ResourceManager.GetString("Type_Fairy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighting.
        /// </summary>
        public static string Type_Fighting {
            get {
                return ResourceManager.GetString("Type_Fighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        public static string Type_Fire {
            get {
                return ResourceManager.GetString("Type_Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flying.
        /// </summary>
        public static string Type_Flying {
            get {
                return ResourceManager.GetString("Type_Flying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghost.
        /// </summary>
        public static string Type_Ghost {
            get {
                return ResourceManager.GetString("Type_Ghost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grass.
        /// </summary>
        public static string Type_Grass {
            get {
                return ResourceManager.GetString("Type_Grass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground.
        /// </summary>
        public static string Type_Ground {
            get {
                return ResourceManager.GetString("Type_Ground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice.
        /// </summary>
        public static string Type_Ice {
            get {
                return ResourceManager.GetString("Type_Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Type_Normal {
            get {
                return ResourceManager.GetString("Type_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison.
        /// </summary>
        public static string Type_Poison {
            get {
                return ResourceManager.GetString("Type_Poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychic.
        /// </summary>
        public static string Type_Psychic {
            get {
                return ResourceManager.GetString("Type_Psychic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock.
        /// </summary>
        public static string Type_Rock {
            get {
                return ResourceManager.GetString("Type_Rock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel.
        /// </summary>
        public static string Type_Steel {
            get {
                return ResourceManager.GetString("Type_Steel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        public static string Type_Water {
            get {
                return ResourceManager.GetString("Type_Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Pokémon cannot be paralysed (PAR).
        /// </summary>
        public static string TypeStatusImmunity_Electric {
            get {
                return ResourceManager.GetString("TypeStatusImmunity_Electric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Pokémon cannot be burned (BRN).
        /// </summary>
        public static string TypeStatusImmunity_Fire {
            get {
                return ResourceManager.GetString("TypeStatusImmunity_Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Pokémon cannot be frozen (FRZ).
        /// </summary>
        public static string TypeStatusImmunity_Ice {
            get {
                return ResourceManager.GetString("TypeStatusImmunity_Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison Pokémon cannot be poisoned (PSN).
        /// </summary>
        public static string TypeStatusImmunity_Poison {
            get {
                return ResourceManager.GetString("TypeStatusImmunity_Poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel Pokémon cannot be poisoned (PSN).
        /// </summary>
        public static string TypeStatusImmunity_Steel {
            get {
                return ResourceManager.GetString("TypeStatusImmunity_Steel", resourceCulture);
            }
        }
    }
}
